### ISSUE TITLE
[崩溃] "type": "type"

### ISSUE THREAD

**Issue by Phoupraw** [SettingDust/ModSets#1]
`config/modsets/rules/example.json`:
```json
{
  "text": {
    "text": "My first rule set",
    "bold": true,
    "color": "green"
  },
  "description": "Awwww",
  "rules": [
    {
      "text": "text",
      "description": "tooltip",
      "controller": {
        "type": "type"
      }
    }
  ]
}
```
crash: [minecraft-exported-crash-info-2023-07-25T12-33-49.zip](https://github.com/SettingDust/ModSets/files/12157125/minecraft-exported-crash-info-2023-07-25T12-33-49.zip)

**Comment by SettingDust** [comment]
你的配置不对，type 不能是 type，这个只是示例，不是可以直接使用的

**Comment by SettingDust** [comment]
I'll update the README for avoiding confusing

**Comment by Phoupraw** [comment]
`config/modsets/rules/mods_group_example.json`:
```json
{
  "text": "The mods group",
  "description": "Text Text",
  "controller": {
    "type": "mods_group",
    "collapsed": false,
    "mods": [
      
    ]
  }
}
```
崩溃报告：[minecraft-exported-crash-info-2023-07-25T12-47-46.zip](https://github.com/SettingDust/ModSets/files/12157186/minecraft-exported-crash-info-2023-07-25T12-47-46.zip)

**Comment by SettingDust** [comment]
controller 是 rule 的属性，而不是根属性，请参考 https://github.com/SettingDust/ModSets/blob/main/example_rules.json?rgh-link-date=2023-07-25T04%3A44%3A10Z 编写

controller is prop of rule instead of root. Refer to https://github.com/SettingDust/ModSets/blob/main/example_rules.json?rgh-link-date=2023-07-25T04%3A44%3A10Z

**Comment by Phoupraw** [comment]
```json
{
  "text": {
    "text": "My first rule set",
    "bold": true,
    "color": "green"
  },
  "description": "Awwww",
  "rules": [
    {
      "text": "The mods group",
      "description": "Text Text",
      "controller": {
        "type": "mods_group",
        "collapsed": false,
        "mods": [
          
        ]
      }
    }
  ]
}
```
![image](https://github.com/SettingDust/ModSets/assets/50520903/c7b5ab10-141d-4635-bba1-5d730093153d)
[latest.log](https://github.com/SettingDust/ModSets/files/12157218/latest.log)

**Comment by Phoupraw** [comment]
我复制了 https://github.com/SettingDust/ModSets/blob/main/example_rules.json 到`config/modsets/rules/mods_group_example.json`，结果
![image](https://github.com/SettingDust/ModSets/assets/50520903/812438c2-3df1-4937-bb31-a737655a3108)
[latest.log](https://github.com/SettingDust/ModSets/files/12157243/latest.log)

**Comment by SettingDust** [comment]
这是个问题，你可以先把 boolean 规则删除了，我得复现一下试试看什么情况

**Comment by SettingDust** [comment]
第二个 null 是因为 mod set 不存在，也就是你应该没有 sodium，我会加一个合适的提示

**Comment by SettingDust** [comment]
fixed in https://modrinth.com/mod/mod-sets/version/1.0.3+1.20.1
