### ISSUE TITLE
Adding this mod causes the game to fail to launch

### ISSUE THREAD

**Issue by hanweiyyds** [SettingDust/ModSets#11]
minecraft版本: 1.20.1
forge版本: 47.20
模组版本: 1.6.0+sha.7d9de3c
添加模组导致游戏无法启动, 单独加载此模组也是一样的结果
崩溃日志: https://pastebin.com/pBaXbgnN

**Comment by SettingDust** [comment]
https://modrinth.com/mod/mod-sets/version/r4XWGB9a
