### ISSUE TITLE
"Save Changes" and "Undo" buttons swapped (on specific condition)

### ISSUE THREAD

**Issue by DEN-SNIPER** [SettingDust/ModSets#13]
(Sorry for bad English, if it's here)
Let's assume that i created 2 rules and 2 modsets:
![изображение](https://github.com/SettingDust/ModSets/assets/47086772/c46c315e-578a-4782-a1b7-9165b66bc806)

Then i am trying to disable "Client mods" and this happens:
![Bug](https://github.com/SettingDust/ModSets/assets/47086772/033788d0-74cd-4f25-b039-bc982dd29326)

It's not working, But if i do "Undo" button:
![b](https://github.com/SettingDust/ModSets/assets/47086772/5f490c45-aeee-4de7-9547-de177a55162e)

Now it's working and if i do this:
![bug2](https://github.com/SettingDust/ModSets/assets/47086772/e2524880-4ecf-4c79-909d-4a5dae357adb)

It's also working (I showed here wrong tab but just trust me). BUT if i swap "Rule" and "Modlist" tabs (swap the names of "1.json" and "2.json" files) the bug occurs from "other side":
![bug3](https://github.com/SettingDust/ModSets/assets/47086772/e9a3a3fd-6dfe-4576-b24e-c3e558e129d7)
![bug4](https://github.com/SettingDust/ModSets/assets/47086772/96a84d64-107c-4b06-b57a-12da257dbd18)
![bug5](https://github.com/SettingDust/ModSets/assets/47086772/e41c0d15-f396-4ed1-af5a-75308670c08b)

There is config files if needed:
[1.json](https://github.com/user-attachments/files/15908296/1.json)
[2.json](https://github.com/user-attachments/files/15908297/2.json)
[modsets.json](https://github.com/user-attachments/files/15908298/modsets.json)

I want to implement this mod in my modpack but this bug makes everything worse.

**Comment by SettingDust** [comment]
It's looks like a bug of YACL. But YACL seems dropped 1.19.2 support. You can try to open an issue on their Github and link back for tracking
