### ISSUE TITLE
Support Fabric Loader 0.16.1+

### ISSUE THREAD

**Issue by oliclice** [SettingDust/ModSets#15]
I wrote the rules according to the documentation, but after disabling the mods and restarting the game, the mods still worked.I've tried a lot of things and it didn't work, maybe it's a bug.
Below is a screenshot.
<img width="1280" alt="Code_y5rI2TmIHr" src="https://github.com/user-attachments/assets/5a37718e-c886-465b-a5c5-ec173281ecd6">
<img width="1280" alt="javaw_V7xf03Gilj" src="https://github.com/user-attachments/assets/51473bd1-ad11-4c67-9309-3fa8f75055dc">

**Comment by SettingDust** [comment]
发个加载了不该加载的模组的日志看看

**Comment by SettingDust** [comment]
暂时不支持 FabricLoader 0.16.1 及以上

**Comment by SettingDust** [comment]
https://modrinth.com/mod/mod-sets/version/1.8.0 应该修复了这个问题
