### ISSUE TITLE
Help needed: Could not understand how to use the mod

### ISSUE THREAD

**Issue by ZotyDev** [SettingDust/ModSets#16]
Hi! Thanks for creating this mod, it is exactly what I was searching for. Sadly, I couldn't understand how to properly use the mod, could you provide more instructions? Perhaps, linking a project that uses the mod and all its features.
Once again, thank you for your work!

**Comment by SettingDust** [comment]
The example is using that I guess

https://www.google.com/search?q=%22Mod+Sets%22+%22inurl%3Amodpack+OR+inurl%3Amodpacks%22+site%3Amodrinth.com+OR+site%3Acurseforge.com
