### ISSUE TITLE
Config button crashes game (Forge 1.20.1)

### ISSUE THREAD

**Issue by QuantumBlur314** [SettingDust/ModSets#18]
I have no other mods enabled, because Mod Sets was also crashing over embeddium complaints earlier.
![minecraft error mod sets](https://github.com/user-attachments/assets/eced00b0-ddd5-4700-ba0e-e49bc35aeb5b)

clicking Mods>mod sets> config crashes with this error:
"
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	YetAnotherConfigLib (yet_another_config_lib_v3), Version: 3.5.0+1.20.1-forge
		at TRANSFORMER/yet_another_config_lib_v3@3.5.0+1.20.1-forge/dev.isxander.yacl3.gui.YACLScreen.lambda$init$4(YACLScreen.java:89)
"
I know it says it's an issue with configlib, but since its page listed a fabric version of Kotlin as a dependency, i figured maybe its other stated dependencies were also incorrect, and opted to ask here.

**Comment by QuantumBlur314** [comment]
nvm it's this, unrelated.  closing #https://github.com/isXander/YetAnotherConfigLib/issues/208#

**Comment by SettingDust** [comment]
use sinytra connector and use yacl fabric
