### ISSUE TITLE
`modsets.json` doesn't generate

### ISSUE THREAD

**Issue by thimblebird** [SettingDust/ModSets#20]
https://github.com/user-attachments/assets/2b7bc960-5c6b-4023-ad8f-23113a508cc9

log: https://mclo.gs/pfrArh4

**Comment by SettingDust** [comment]
oh. The filename is wrong. Fixed in 1.10.3. Publishing

**Comment by SettingDust** [comment]
https://github.com/SettingDust/ModSets/actions/runs/11829520934/job/32961467839

**Comment by thimblebird** [comment]
works now 👍🏻
