### ISSUE TITLE
Disabled mods are still loaded

### ISSUE THREAD

**Issue by Felix14-v2** [SettingDust/ModSets#3]
**Description**
As you can see, removing mod ID from the list doesn't do anything:
<details>
 <summary>Images</summary>

![image](https://github.com/SettingDust/ModSets/assets/75726196/5aaf898c-022a-48df-b1ad-a9c83ef44b2e)
![image](https://github.com/SettingDust/ModSets/assets/75726196/de758659-7f18-4f75-986f-5972c338cc83)

</details>

**To reproduce**
1. Install Mod Sets and its dependencies
2. Install any other mod ([Sodium](https://modrinth.com/mod/sodium), for example)
3. Launch the game
4. Remove `sodium` from the Sodium group
5. Restart the game
6. Sodium is still loaded

**Additional**
Maybe I'm just wrong in understanding how this feature should work ._.

**Comment by SettingDust** [comment]
That's a bug I noticed yesterday. For now you can add sodium to `disabled mods.json` manually.
https://discord.com/channels/780023008668287017/1133397178673537114/1133397178673537114

**Comment by SettingDust** [comment]
Wait. Remove the mod from mod sets isn't for disable mod. If you wanna disable mod, you should change the value in rule set. The mod id always target the mod as a singleton mod set if there isn't defined mod sets. The mod set is using for rules to operate multiple mods

**Comment by SettingDust** [comment]
That's a problem. Maybe I should give a option to hide the mod sets config screen since it is for developer of modpack instead of users

**Comment by SettingDust** [comment]
close https://github.com/SettingDust/ModSets/commit/32341da3a36944c4154940b198941a34c50becf7
https://modrinth.com/project/b313lC4Y/version/tVCvnPYp
