### ISSUE TITLE
"rules_group" controller type overwrites text of individual rules

### ISSUE THREAD

**Issue by Zaroz** [SettingDust/ModSets#7]
I wanted to group up mods with categories that could be collapsed but all of the text in the individual rules got overwritten in the GUI.
Here is my code:
[gist](https://gist.github.com/Zaroz/f4a0d43a5dc2b3ce3e9b4f7d925cf2f3)

And this is what it looks like:
![mc,iss](https://github.com/SettingDust/ModSets/assets/22653076/da47ec18-f077-4f21-9f69-e229c3f4cf3a)

**Comment by SettingDust** [comment]
fixed in 1.3.3

**Comment by SettingDust** [comment]
![图片](https://github.com/SettingDust/ModSets/assets/19922286/79164b63-81c9-4fa3-9285-ae70f04f57aa)
